<a href="https://colab.research.google.com/github/lokeshreddy82/practise/blob/main/numpy_module_preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import numpy as np

In [34]:
pd=np.array([[1,2,3],[4,5,6]])
pd.shape


(2, 3)

In [36]:
n=np.reshape(pd,(3,2),order="c")
n

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
row,column=pd.shape
print(row)
print(column)

2
3


In [42]:
s=np.full((3,3),5)
s

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [47]:
a=np.empty([3,3])
a.fill(0)
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
l=np.transpose(n)
l

array([[1, 3, 5],
       [2, 4, 6]])

In [52]:
lokesh=np.linspace(10,100,5)
lokesh

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [65]:
ganesh=np.random.random((3,5))
ganesh

array([[0.08067144, 0.86490978, 0.39882723, 0.53942509, 0.20398547],
       [0.6084303 , 0.93570897, 0.05989844, 0.31557932, 0.34495725],
       [0.78798494, 0.7086702 , 0.99004609, 0.90785157, 0.8956822 ]])

In [58]:
akhil=np.random.randint(10,100,(3,4))
akhil

array([[56, 20, 80, 11],
       [69, 34, 39, 37],
       [79, 13, 97, 48]])

In [64]:
nana=np.linspace(10,50,5)
nana

array([10., 20., 30., 40., 50.])

In [69]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
s=np.asarray(list1)
m=np.asarray(list2)
print(s)
print(m)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [76]:
a=[1,2,3]
b=[4,5,6]
print(a+b)
k=np.divide(a,b)
k

[1, 2, 3, 4, 5, 6]


array([0.25, 0.4 , 0.5 ])